Update prompt and terminal title.

diff --git a/dist/bashrc b/dist/bashrc
--- a/dist/bashrc
+++ b/dist/bashrc
@@ -1,6 +1,47 @@
 #
 # This file was automatically generated from 'setup/profile/generate.sh'
-#
+########################################
+# PS1 Reference
+# (the below is just an example)
+########################################
+
+# \[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]\n\$
+
+# # The first part sets the xterm title (usually shows in the titlebar of the window).
+
+# \[        -Starts a sequence of escapes.
+# \e]0;     -Starts the xterm title prompt expression.
+# \w        -Display the current working directory.
+# \a        -Equal to \007 (system bell).  In this case used to end the xterm title prompt.
+# \]        -End escape sequence.
+
+# # The second part sets the actual PS1 prompt
+
+# \n        -Start with a newline.
+# \[        -Start another sequence of escapes.
+# \e[32m    -Sets the color to green.
+# \]        -End escape sequence.
+
+# \u@\h     -User at host name.  This and the \w below are the visible parts of the prompt.
+
+# \[        -Begin another escape sequence.
+# \e[33m    -Set color to red.
+# \]        -End escape sequence.
+
+# \w        -Display working directory in prompt.
+
+# \[        -Begin another sequence.
+# \e[0m     -Reset escape formatting to default.
+# \]        -End sequence.
+
+# \n        -Another newline.
+# \$        -The final command line prompt character.
+
+########################################
+# For more information on PS1 escape sequences, see:
+# https://tldp.org/HOWTO/Bash-Prompt-HOWTO/bash-prompt-escape-sequences.html
+# https://wiki.archlinux.org/title/Bash/Prompt_customization
+########################################
 
 # If not running interactively, don't do anything
 case $- in
@@ -25,11 +66,17 @@ FANCY_PROMPT=true
 # reload .env file from 'PROMPT_COMMAND'
 #PROMPT_COMMAND_ENV_RELOAD=true
 
+# force __prompt_command to always be first when setting PROMPT_COMMAND
+#PROMPT_COMMAND_ALWAYS_FIRST=false
+
 # set force_color_prompt=true
 #FORCE_COLOR_PROMPT=true
 
 # umask override value for folders specified in UMASK_OVERRIDE_DIRS
 UMASK_OVERRIDE=0002
+
+# insert new line before umask override status message
+#UMASK_OVERRIDE_DISPLAY_MULTILINE=true
 
 # UMASK_OVERRIDE_DIRS and UMASK_OVERRIDE_EXCLUDE_DIRS should be
 # space separated, e.g. '/path/one /path/two /path/three ...'
@@ -83,9 +130,9 @@ shopt -s checkwinsize
 #shopt -s globstar
 
 # set variable identifying the chroot you work in (used in the prompt below)
-# (for debian-based systems only)
+# (for debian-based systems only; to check: `cat /etc/os-release | grep ID_LIKE | awk -F'=' '{print $2}'`)
 # if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
-#     debian_chroot=$(cat /etc/debian_chroot)
+#   debian_chroot=$(cat /etc/debian_chroot)
 # fi
 
 # Load ~/.env if it exists
@@ -104,7 +151,7 @@ is_interactive_mode() {
 # Basic Output
 errcho() { >&2 echo -e "$@"; }
 output() { ! is_interactive_mode || errcho "\033[0;2m$@\033[0m"; }
-showerr() { output $?; }
+flusherr() { output $?; }
 
 # Fancy Logging
 logmsg() {
@@ -158,19 +205,27 @@ equals() { is_equal "$@" 2>/dev/null; }
 
 shellos() {
   test -r /etc/os-release && . /etc/os-release
-  local id="" os="" os_like="" uname="$(uname -s | awk -F'_' '{print $1}')"
+  local uname="$(uname -s | awk -F'_' '{print $1}')"
+  local id="" os="" os_like=""
   shopt -s nocasematch
   case $uname in
     Linux)
-      test -r /etc/os-release && . /etc/os-release
-      case $ID in
-        ubuntu|rhel)
-          id="$ID"
-          os="$NAME"
-          os_like="$ID_LIKE"
-          ;;
-        *) ;;
-      esac
+      # A slightly less targeted (but just as effective) approach is to source the /etc/os-release,
+      # e.g. `test -r /etc/os-release && . /etc/os-release`
+      if test -r /etc/os-release ; then
+        local os_release_vars="ID ID_LIKE NAME"
+        for var in $os_release_vars; do
+          eval "$var="$(cat /etc/os-release | grep "^$var\=.*$" | awk -F'=' '{print $2}')
+        done
+        case $ID in
+          ubuntu|rhel)
+            id="$ID"
+            os="$NAME"
+            os_like="$ID_LIKE"
+            ;;
+          *) ;;
+        esac
+      fi
       ;;
     Darwin) os="$uname"; id=macos;;
     MINGW64) os="Windows"; id=windows;;
@@ -278,6 +333,9 @@ fi
 
 ### Custom PS1 and PROMPT_COMMAND Handling
 
+EXIT=0
+ARGC=0
+ARGV=''
 __save_prompt_command() { _PROMPT_COMMAND=$PROMPT_COMMAND; }
 __save_ps1() { _PS1=$PS1; }
 
@@ -291,7 +349,7 @@ __ps1_color() {
 
 # display last exit code status
 __exit_code_status() {
-  local checkmark=✓ xkmark=✗ checkmark_bold=✔ xmark_bold=✘ arrow_right=➜
+  local checkmark=✓ xmark=✗ checkmark_bold=✔ xmark_bold=✘ arrow_right=➜
   local code="${1:-0}" ps1_prompt_status=""
   if is "${FANCY_PROMPT:-false}" ; then
     if [ -z "$code" -o "$code" = "0" ]; then
@@ -306,7 +364,8 @@ __exit_code_status() {
 }
 
 # display arguments
-__prompt_args() { [ -z "$1" ] || printf "(%s) " "$@"; }
+__prompt_args() { [ $# -eq 0 ] || printf "(%s) " "$@"; }
+__title_status() { local code=${1:-0}; [ $code -eq 0 ] || printf "%s | " $code; }
 
 # reload env
 __prompt_command_env_reload() {
@@ -317,26 +376,34 @@ __prompt_command_env_reload() {
 }
 
 # Main function for updating $PROMPT_COMMAND
-__main_prompt_command() {
+# if using this function to manipulate PS1, this function should always be first when setting PROMPT_COMMAND
+__prompt_command() {
+  # Cache initial exit code to avoid reset from env load
+  local exit=${?##0}
+
+  # load .env file before setting other vars
   __prompt_command_env_reload
+
+  # Hack to always keep exit code up-to-date
+  # TODO: this is needed because PS1_PREFIX seems to reset the error code .. why?
+  EXIT=$exit
 }
 
 # Main function for updating $PS1
-__main_ps1() {
-  local code=${?##0}
-  __exit_code_status $code
+__ps1() {
+  __exit_code_status $EXIT
   __prompt_args "$@"
 }
 
-if is "${PROMPT_COMMAND_FIRST:-true}" ; then
+if is "${PROMPT_COMMAND_ALWAYS_FIRST:-true}" ; then
   # ensure '__prompt_command' is first
   if [ -n "$PROMPT_COMMAND" ]; then
-    PROMPT_COMMAND='__main_prompt_command "$@";'"$PROMPT_COMMAND"
+    PROMPT_COMMAND='__prompt_command "$@";'"$PROMPT_COMMAND"
   else
-    PROMPT_COMMAND='__main_prompt_command "$@"'
+    PROMPT_COMMAND='__prompt_command "$@"'
   fi
 else
-  PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND;}"'__main_prompt_command "$@"'
+  PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND;}"'__prompt_command "$@"'
 fi
 __save_prompt_command
 
@@ -349,12 +416,14 @@ if is_linux ; then
 else
   # Use 'parse_hostname' instead of '\h' for advanced customization
   if [ "$color_prompt" = "yes" ]; then
-    PS1="\[\033[01;34m\]\u\[\033[0m\]@\[\033[01;32m\]\$(parse_hostname 100 '-')\[\033[00m\]:\[\033[01;34m\]\w\[\033[0;32m\]\$(parse_git_branch)\[\033[00m\]\$ "
+    PS1='$(__ps1_color $C_BLUE_BOLD)\u$(__ps1_color)@$(__ps1_color $C_GREEN_BOLD)$(parse_hostname 100 '-')$(__ps1_color):$(__ps1_color $C_BLUE_BOLD)\w$(__ps1_color $C_GREEN_BOLD)$(parse_git_branch)$(__ps1_color)\$ '
   else
-    PS1="\u@\$(parse_hostname 10 '-'):\w\$(parse_git_branch)\$ "
+    PS1='\u@$(parse_hostname 100 '-'):\w$(parse_git_branch)\$ '
   fi
 fi
-PS1='$(__main_ps1 "$@")'$PS1
+
+PS1_PREFIX='\[\e]0;$(__title_status $?)$(__prompt_args "$@")\u@$(parse_hostname 100 '-'):\w\a\]'
+PS1=$PS1_PREFIX'$(__ps1 "$@")'$PS1
 __save_ps1
 ###
 
@@ -376,7 +445,9 @@ __umask_default() {
 }
 
 __umask_override() {
-  printf "\033[0;2m%s\033[0m: \033[91;2m%s\033[0m=>\033[92;2m%s\033[0m\n" "Overriding default umask" "$UMASK_DEFAULT" "$UMASK_OVERRIDE" >&2
+  local prefix=""
+  ! is "${UMASK_OVERRIDE_DISPLAY_MULTILINE:-false}" || prefix='\n'
+  printf "$prefix\033[0;2m%s\033[0m: \033[91;2m%s\033[0m=>\033[92;2m%s\033[0m\n" "Overriding default umask" "$UMASK_DEFAULT" "$UMASK_OVERRIDE" >&2
   export UMASK=$UMASK_OVERRIDE
 }
 
@@ -400,7 +471,7 @@ __umask_hook() {
 }
 
 # Append `;` if PROMPT_COMMAND is not empty
-PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND;}__umask_hook"
+PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND;}"__umask_hook
 __save_prompt_command
 # ------------------------------------------------------------
 # -- END --
