PS1 updates.

diff --git a/dist/bashrc b/dist/bashrc
--- a/dist/bashrc
+++ b/dist/bashrc
@@ -17,6 +17,7 @@ shopt login_shell >/dev/null || cd ~
 # -- BEGIN -- '$HOME/Shared/etc/profile.d/01-env.sh'
 # ------------------------------------------------------------
 FORCE_COLOR_PROMPT_WINDOWS=true
+FANCY_PROMPT=true
 
 UMASK_OVERRIDE=0002
 # Space separated e.g. '/path/one /path/two /path/three ...'
@@ -165,12 +166,34 @@ command -v realpath >/dev/null || alias realpath='__realpath'
 
 # -- BEGIN -- '$HOME/Shared/etc/profile.d/03-prompt.sh'
 # ------------------------------------------------------------
+# define colors for easy reference
+C_DEFAULT=$'\033[00m'; C_BOLD=$'\033[01m'; C_REVERSE=$'\033[07m'
+C_RED=$'\033[00;31m'; C_GREEN=$'\033[00;32m'; C_YELLOW=$'\033[00;33m'
+C_BLUE=$'\033[00;34m'; C_PURPLE=$'\033[00;35m'; C_CYAN=$'\033[00;36m'
+C_RED_BOLD=$'\033[01;31m'; C_GREEN_BOLD=$'\033[01;32m'; C_YELLOW_BOLD=$'\033[01;33m'
+C_BLUE_BOLD=$'\033[01;34m'; C_PURPLE_BOLD=$'\033[01;35m'; C_CYAN_BOLD=$'\033[01;36m'
+
+# 🚨
+control_c() {
+  local err="$?"
+  printf "\n⛔ ${C_RED_BOLD}✗${C_DEFAULT} ${C_RED}(%s)${C_DEFAULT} ${C_BOLD}%s${C_DEFAULT} ⛔" "$err" "Operation cancelled by user"
+  # To fully exit the script, use 'exit' instead of 'return'
+  return $err;
+}
+if is "${FANCY_PROMPT:-false}" ; then
+  trap control_c SIGINT SIGTERM SIGHUP
+fi
+
+# load .env file
+load_env() { [ ! -r "$HOME/.env" ] || . "$HOME/.env"; }
+
 # get current git branch
 parse_git_branch() {
   git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
 }
 export -f parse_git_branch
 
+# custom hostname parsing
 parse_hostname() {
   local arg=${1:-1} replace=${2:-.}
   local count=$(hostname | grep -o '\.' | wc -l | xargs echo)
@@ -203,21 +226,57 @@ if [ -n "$force_color_prompt" ]; then
   fi
 fi
 
-# Example of using debian_chroot in PS1
-# if [ "$color_prompt" = yes ]; then
-#     PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
-# else
-#     PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
-# fi
+# Custom PS1 and PROMPT_COMMAND Handling
+__ps1_color() {
+  local _PS1_OPEN_ESC=$'\001'
+  local _PS1_CLOSE_ESC=$'\002'
+  local _PS1_FG="${1:-$C_DEFAULT}"
+  echo "${_PS1_OPEN_ESC}${_PS1_FG}${_PS1_CLOSE_ESC}"
+}
 
-# Use 'parse_hostname' instead of '\h' for advacned customization
-if [ "$color_prompt" = "yes" ]; then
-  _PS1="\[\033[01;34m\]\u\[\033[0m\]@\[\033[01;32m\]\$(parse_hostname 10 '-')\[\033[00m\]:\[\033[01;34m\]\w\[\033[0;32m\]\$(parse_git_branch)\[\033[00m\]\$ "
+# display last exit code status
+__exit_code_status() {
+  local checkmark=✓ xkmark=✗ checkmark_bold=✔ xmark_bold=✘ arrow_right=➜
+  local code="${1:-0}" ps1_prompt_status=""
+  if is "${FANCY_PROMPT:-false}" ; then
+    if [ -z "$code" -o "$code" = "0" ]; then
+      ps1_prompt_status="$(__ps1_color $C_GREEN)${checkmark_bold}$(__ps1_color) "
+    else
+      ps1_prompt_status="$(__ps1_color $C_RED_BOLD)${xmark_bold}$(__ps1_color) "
+      # uncomment netx line to display exit the code
+      #ps1_prompt_status+="$(__ps1_color $C_RED)($code)$(__ps1_color) "
+    fi
+    echo "$ps1_prompt_status"
+  fi
+}
+
+__update_prompt_command() {
+  local code=$? color_prompt="${1:-""}"
+  local ps1_prompt_status="$(__exit_code_status $code)"
+  set -a; load_env; set +a >/dev/null
+}
+
+PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND;}__update_prompt_command"
+
+if is_linux ; then
+  if [ "$color_prompt" = yes ]; then
+    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
+  else
+    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
+  fi
 else
-  _PS1="\u@\$(parse_hostname 10 '-'):\w\$(parse_git_branch)\$ "
+  # Use 'parse_hostname' instead of '\h' for advacned customization
+  if [ "$color_prompt" = "yes" ]; then
+    PS1="\[\033[01;34m\]\u\[\033[0m\]@\[\033[01;32m\]\$(parse_hostname 10 '-')\[\033[00m\]:\[\033[01;34m\]\w\[\033[0;32m\]\$(parse_git_branch)\[\033[00m\]\$ "
+  else
+    PS1="\u@\$(parse_hostname 10 '-'):\w\$(parse_git_branch)\$ "
+  fi
 fi
+PS1='$(code=${?##0};__exit_code_status $code)'$PS1
+###
+
+# cleanup
 unset color_prompt force_color_prompt
-export PS1=$_PS1
 # ------------------------------------------------------------
 # -- END --
 
@@ -238,7 +297,7 @@ __umask_override() {
   export UMASK=$UMASK_OVERRIDE
 }
 
-_umask_hook() {
+__umask_hook() {
   if [ "$UMASK_OVERRIDE" != "$UMASK_DEFAULT" -a -n "$UMASK_OVERRIDE_DIRS" ]; then
     for d in $UMASK_OVERRIDE_DIRS; do
       if [ -d "$d" ]; then
@@ -258,7 +317,7 @@ _umask_hook() {
 }
 
 # Append `;` if PROMPT_COMMAND is not empty
-PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND;}_umask_hook"
+PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND;}__umask_hook"
 # ------------------------------------------------------------
 # -- END --
 
